# Generated by Django 5.1.4 on 2024-12-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='garage',
            field=models.IntegerField(default=0),
        ),
    ]
