# Generated by Django 5.1.4 on 2024-12-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_property_property_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='built_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sqft',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
